### ISSUE TITLE
The code is not working

### ISSUE THREAD

**Issue by hAbd0u** [brenovambaster/WhatsApp-last-seen#1]
Hello,
The code is not working using the WhatsApp web, would you check it?

**Comment by brenovambaster** [comment]
Hi, sorry for the delay in responding. 
I hadn't seen the bug. I will analyze what happened.

**Comment by brenovambaster** [comment]
@hAbd0u, 
Please follow these steps:
1 )Open whatsapp web (https://web.whatsapp.com/)
2) Open the chat;
3) Open the devTools
4) Paste the code into the console.

```js
let b = setInterval(() => {
    let hora = new Date;
    let a = document.getElementsByClassName("_2YPr_ i0jNr selectable-text copyable-text");
    if (a.length == 0) {
        console.log("off");
    } else if (a[0].title == "online") {
        console.log(`online ${hora.getHours()}:${hora.getMinutes()}`);
    }
}, 3000)
b;
```

**Attention, I'm using google chrome.**
**Test and let me know if it worked.**
### **Inappropriate use of this tool is your responsibility;**

**Comment by hAbd0u** [comment]
Hello @brenovambaster,
I believe it is still not working even the tested browser is Chrome 106.0.52.
